name: Build and Deploy Angular App

on:
  push:
    branches:
      - master  # Déclenche la pipeline uniquement sur la branche master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Cloner le dépôt

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.20.3'  # Configuration de la version de Node.js requise

      - name: Install dependencies
        run: npm install  # Installer les dépendances de l'application

      - name: Build the Angular application
        run: npm run build --prod  # Construire l'application Angular

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ce job dépend du job 'build'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Cloner à nouveau le dépôt

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CHAYMAASECRET }}
          publish_dir: ./dist/app2/browser  # Dossier de build de l'application Angular